version: '3.8'  
  
services:  
  web:  
    build: .  
    volumes:  
      - .:/app  
      - static_volume:/app/staticfiles  
      - media_volume:/app/media  
    ports:  
      - "8000:8000"  
    environment:  
      - DEBUG=1  
      - MYSQL_HOST=mysql  
      - MYSQL_DATABASE=mydb  
      - MYSQL_USER=myuser  
      - MYSQL_PASSWORD=mypassword  
      - DJANGO_SUPERUSER_USERNAME=admin  
      - DJANGO_SUPERUSER_PASSWORD=admin  
      - DJANGO_SUPERUSER_EMAIL=admin@example.com  
    depends_on:  
      mysql:  
        condition: service_healthy  
    restart: unless-stopped  
  
  mysql:  
    image: mysql:8.0  
    command: --default-authentication-plugin=mysql_native_password  
    environment:  
      MYSQL_DATABASE: mydb  
      MYSQL_USER: myuser  
      MYSQL_PASSWORD: mypassword  
      MYSQL_ROOT_PASSWORD: rootpassword  
    volumes:  
      - mysql_data:/var/lib/mysql  
    healthcheck:  
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]  
      interval: 5s  
      timeout: 10s  
      retries: 10  
    ports:  
      - "3306:3306"  
  
volumes:  
  mysql_data:  
  static_volume:  
  media_volume: