# Generated by Django 5.1.6 on 2025-02-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_value', models.FloatField()),
                ('y_value', models.FloatField()),
                ('temperature', models.FloatField()),
            ],
        ),
    ]
