# Generated by Django 5.1.6 on 2025-05-11 16:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_calculationresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='solution',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='table',
            name='title',
            field=models.TextField(default='Untitled'),
        ),
        migrations.AlterField(
            model_name='table',
            name='points',
            field=models.ManyToManyField(related_name='tables', to='main.point'),
        ),
        migrations.CreateModel(
            name='CalculationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Без названия', max_length=200, verbose_name='Название расчета')),
                ('param_a', models.FloatField()),
                ('param_b', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('iterations', models.IntegerField(blank=True, null=True, verbose_name='Количество итераций')),
                ('exec_time', models.FloatField(blank=True, null=True, verbose_name='Время выполнения (сек)')),
                ('algorithm', models.CharField(blank=True, max_length=100, null=True, verbose_name='Алгоритм')),
                ('average_op', models.FloatField(blank=True, null=True, verbose_name='Средняя относительная погрешность (%)')),
                ('table_data', models.TextField(blank=True, null=True, verbose_name='Данные таблицы')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.table')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Результат расчета',
                'verbose_name_plural': 'Результаты расчетов',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_images/', verbose_name='Изображение')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('calculation_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.calculationresult')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
